### PR TITLE
Added addMembership() method, updated constants.

### PR DESCRIPTION
**Pull request by hillarynichols**

### CODE REVIEW

**Comment by aheritier** [comment]
@msohn could you review and apply this PR please ? This method is mandatory with current GitHub APIs.

**Comment by cvrebert** [comment]
egit-github ironically doesn't accept GitHub pull requests; you have to submit changes via their Gerrit instance instead. See http://wiki.eclipse.org/EGit/Contributor_Guide#Contributing_Patches for more info on the process.

**Comment by aheritier** [comment]
egit-github is more and more deprecated everyday. Many things are missing with recent API changes. @github should probably better to provide its own Java API without any link with egit/eclipse and stop to promote this one ...

**Comment by msohn** [comment]
@github started egit-github but they disappeared from the project around 2 years ago

**Comment by zzzzpaul** [comment]
#17

**Pull request closed without merging**
